name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  android_test_job:
    name: Android Test
    runs-on: macos-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          script: ./gradlew connectedDebugAndroidTest
      - name: Upload Android Test Reports
        if: ${{always()}}
        uses: actions/upload-artifact@v2
        with:
          name: android-test-reports
          path: '**/build/reports/androidTests/'